import type { FileChange } from '../schemas/fix-proposal.schema';

/**
 * Applies every change targeting one file to that file's content. Changes
 * are applied bottom-to-top (highest startLine first) so replacing one
 * range never shifts the line numbers a not-yet-applied change further up
 * the file still relies on.
 */
export function applyChangesToFile(fileContent: string, changes: FileChange[]): string {
  const sorted = [...changes].sort((a, b) => b.startLine - a.startLine);
  let lines = fileContent.split('\n');

  for (const change of sorted) {
    const before = lines.slice(0, change.startLine - 1);
    const after = lines.slice(change.endLine);
    const replacement = change.replacementCode.split('\n');
    lines = [...before, ...replacement, ...after];
  }

  return lines.join('\n');
}

interface DiffLine {
  type: 'context' | 'add' | 'remove';
  content: string;
}

/** Classic LCS line diff. Fine for source-file-sized inputs (this engine caps patches at ~100 changed lines). */
function computeLineDiff(oldLines: string[], newLines: string[]): DiffLine[] {
  const n = oldLines.length;
  const m = newLines.length;
  const lcs: number[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));

  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      lcs[i][j] = oldLines[i] === newLines[j] ? lcs[i + 1][j + 1] + 1 : Math.max(lcs[i + 1][j], lcs[i][j + 1]);
    }
  }

  const result: DiffLine[] = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (oldLines[i] === newLines[j]) {
      result.push({ type: 'context', content: oldLines[i] });
      i += 1;
      j += 1;
    } else if (lcs[i + 1][j] >= lcs[i][j + 1]) {
      result.push({ type: 'remove', content: oldLines[i] });
      i += 1;
    } else {
      result.push({ type: 'add', content: newLines[j] });
      j += 1;
    }
  }
  while (i < n) {
    result.push({ type: 'remove', content: oldLines[i] });
    i += 1;
  }
  while (j < m) {
    result.push({ type: 'add', content: newLines[j] });
    j += 1;
  }

  return result;
}

/**
 * Renders a unified-diff-style string comparing two full file contents.
 * Generated by the backend from verified before/after content — never from
 * the AI's own `patch` field — so what's displayed is always accurate.
 */
export function renderUnifiedDiff(filePath: string, originalContent: string, patchedContent: string): string {
  const diffLines = computeLineDiff(originalContent.split('\n'), patchedContent.split('\n'));
  const header = [`--- a/${filePath}`, `+++ b/${filePath}`];
  const body = diffLines.map((line) => {
    if (line.type === 'context') return ` ${line.content}`;
    if (line.type === 'add') return `+${line.content}`;
    return `-${line.content}`;
  });
  return [...header, ...body].join('\n');
}
